version: '3.8'
services:
  db:
    image: postgres
    restart: always
    environment:
      POSTGRES_USER: fazt
      POSTGRES_PASSWORD: faztpassword
      POSTGRES_DB: nodepg
    ports:
      - 5432:5432